// Generated by supabase gen types typescript --linked
// Replace after linking a Supabase project:
//   supabase link --project-ref <ref>
//   supabase gen types typescript --linked > types/database.types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          role: 'user' | 'moderator' | 'admin'
          name: string | null
          gender: 'male' | 'female' | null
          birth_date: string | null
          country: string | null
          city: string | null
          nationality: string | null
          height: number | null
          weight: number | null
          location: unknown | null
          marital_status: string | null
          children_count: number | null
          education: string | null
          income_level: string | null
          housing: string | null
          willing_to_relocate: boolean | null
          polygyny_attitude: string | null
          hijab_attitude: string | null
          about_self: string | null
          ai_bio: string | null
          ai_bio_status: 'ready' | 'regenerating' | 'rate_limited' | 'pending' | null
          ai_bio_input_hash: string | null
          is_published: boolean | null
          private_mode: boolean | null
          onboarding_completed: boolean | null
          locale: string | null
          theme_preference: string | null
          last_seen_at: string | null
          deletion_status: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id: string
          email: string
          role?: 'user' | 'moderator' | 'admin'
          name?: string | null
          gender?: 'male' | 'female' | null
          birth_date?: string | null
          country?: string | null
          city?: string | null
          nationality?: string | null
          height?: number | null
          weight?: number | null
          location?: unknown | null
          marital_status?: string | null
          children_count?: number | null
          education?: string | null
          income_level?: string | null
          housing?: string | null
          willing_to_relocate?: boolean | null
          polygyny_attitude?: string | null
          hijab_attitude?: string | null
          about_self?: string | null
          ai_bio?: string | null
          ai_bio_status?: 'ready' | 'regenerating' | 'rate_limited' | 'pending' | null
          ai_bio_input_hash?: string | null
          is_published?: boolean | null
          private_mode?: boolean | null
          onboarding_completed?: boolean | null
          locale?: string | null
          theme_preference?: string | null
          last_seen_at?: string | null
          deletion_status?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          role?: 'user' | 'moderator' | 'admin'
          name?: string | null
          gender?: 'male' | 'female' | null
          birth_date?: string | null
          country?: string | null
          city?: string | null
          nationality?: string | null
          height?: number | null
          weight?: number | null
          location?: unknown | null
          marital_status?: string | null
          children_count?: number | null
          education?: string | null
          income_level?: string | null
          housing?: string | null
          willing_to_relocate?: boolean | null
          polygyny_attitude?: string | null
          hijab_attitude?: string | null
          about_self?: string | null
          ai_bio?: string | null
          ai_bio_status?: 'ready' | 'regenerating' | 'rate_limited' | 'pending' | null
          ai_bio_input_hash?: string | null
          is_published?: boolean | null
          private_mode?: boolean | null
          onboarding_completed?: boolean | null
          locale?: string | null
          theme_preference?: string | null
          last_seen_at?: string | null
          deletion_status?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      photos: {
        Row: {
          id: string
          profile_id: string
          storage_path: string | null
          position: number
          status: 'pending' | 'uploaded' | 'processing' | 'processed'
          moderation_status: 'queued' | 'approved' | 'rejected' | 'manual_review'
          moderation_result: Json | null
          moderation_reason: string | null
          variants: Json | null
          phash: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          profile_id: string
          storage_path?: string | null
          position: number
          status?: 'pending' | 'uploaded' | 'processing' | 'processed'
          moderation_status?: 'queued' | 'approved' | 'rejected' | 'manual_review'
          moderation_result?: Json | null
          moderation_reason?: string | null
          variants?: Json | null
          phash?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          profile_id?: string
          storage_path?: string | null
          position?: number
          status?: 'pending' | 'uploaded' | 'processing' | 'processed'
          moderation_status?: 'queued' | 'approved' | 'rejected' | 'manual_review'
          moderation_result?: Json | null
          moderation_reason?: string | null
          variants?: Json | null
          phash?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'photos_profile_id_fkey'; columns: ['profile_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      likes: {
        Row: {
          id: string
          from_user_id: string
          to_user_id: string
          created_at: string | null
        }
        Insert: {
          id?: string
          from_user_id: string
          to_user_id: string
          created_at?: string | null
        }
        Update: {
          id?: string
          from_user_id?: string
          to_user_id?: string
          created_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'likes_from_user_id_fkey'; columns: ['from_user_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'likes_to_user_id_fkey'; columns: ['to_user_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      matches: {
        Row: {
          id: string
          user_a: string
          user_b: string
          created_at: string | null
        }
        Insert: {
          id?: string
          user_a: string
          user_b: string
          created_at?: string | null
        }
        Update: {
          id?: string
          user_a?: string
          user_b?: string
          created_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'matches_user_a_fkey'; columns: ['user_a']; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'matches_user_b_fkey'; columns: ['user_b']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      chats: {
        Row: {
          id: string
          match_id: string
          created_at: string | null
        }
        Insert: {
          id?: string
          match_id: string
          created_at?: string | null
        }
        Update: {
          id?: string
          match_id?: string
          created_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'chats_match_id_fkey'; columns: ['match_id']; referencedRelation: 'matches'; referencedColumns: ['id'] }
        ]
      }
      messages: {
        Row: {
          id: string
          chat_id: string
          sender_id: string
          type: 'text' | 'image' | 'voice'
          content: string
          parent_id: string | null
          status: 'sent' | 'delivered' | 'read' | null
          created_at: string | null
          read_at: string | null
          edited_at: string | null
          original_content: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          chat_id: string
          sender_id: string
          type: 'text' | 'image' | 'voice'
          content: string
          parent_id?: string | null
          status?: 'sent' | 'delivered' | 'read' | null
          created_at?: string | null
          read_at?: string | null
          edited_at?: string | null
          original_content?: string | null
          deleted_at?: string | null
        }
        Update: {
          id?: string
          chat_id?: string
          sender_id?: string
          type?: 'text' | 'image' | 'voice'
          content?: string
          parent_id?: string | null
          status?: 'sent' | 'delivered' | 'read' | null
          created_at?: string | null
          read_at?: string | null
          edited_at?: string | null
          original_content?: string | null
          deleted_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'messages_chat_id_fkey'; columns: ['chat_id']; referencedRelation: 'chats'; referencedColumns: ['id'] },
          { foreignKeyName: 'messages_sender_id_fkey'; columns: ['sender_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'messages_parent_id_fkey'; columns: ['parent_id']; referencedRelation: 'messages'; referencedColumns: ['id'] }
        ]
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          status: 'unread' | 'read' | null
          title_key: string
          body_key: string
          payload: Json | null
          entity_id: string | null
          created_at: string | null
          read_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          status?: 'unread' | 'read' | null
          title_key: string
          body_key: string
          payload?: Json | null
          entity_id?: string | null
          created_at?: string | null
          read_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          status?: 'unread' | 'read' | null
          title_key?: string
          body_key?: string
          payload?: Json | null
          entity_id?: string | null
          created_at?: string | null
          read_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'notifications_user_id_fkey'; columns: ['user_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      notification_preferences: {
        Row: {
          id: string
          user_id: string
          type: string
          enabled: boolean | null
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          enabled?: boolean | null
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          enabled?: boolean | null
        }
        Relationships: [
          { foreignKeyName: 'notification_preferences_user_id_fkey'; columns: ['user_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      push_subscriptions: {
        Row: {
          id: string
          user_id: string
          kind: 'web' | 'apns' | 'fcm' | null
          endpoint: string | null
          auth: string | null
          p256dh: string | null
          device_token: string | null
          device_id: string | null
          locale: string | null
          last_seen_at: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          kind?: 'web' | 'apns' | 'fcm' | null
          endpoint?: string | null
          auth?: string | null
          p256dh?: string | null
          device_token?: string | null
          device_id?: string | null
          locale?: string | null
          last_seen_at?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          kind?: 'web' | 'apns' | 'fcm' | null
          endpoint?: string | null
          auth?: string | null
          p256dh?: string | null
          device_token?: string | null
          device_id?: string | null
          locale?: string | null
          last_seen_at?: string | null
          created_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'push_subscriptions_user_id_fkey'; columns: ['user_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          tbank_payment_id: string | null
          tbank_customer_key: string | null
          status: 'active' | 'expired' | 'cancelled' | 'inactive' | null
          current_period_start: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          tbank_payment_id?: string | null
          tbank_customer_key?: string | null
          status?: 'active' | 'expired' | 'cancelled' | 'inactive' | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          tbank_payment_id?: string | null
          tbank_customer_key?: string | null
          status?: 'active' | 'expired' | 'cancelled' | 'inactive' | null
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'subscriptions_user_id_fkey'; columns: ['user_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
      pricing_plans: {
        Row: {
          code: string
          name_key: string
          description_key: string
          amount_kopecks: number
          currency: string
          period_days: number
          is_active: boolean
          updated_at: string | null
        }
        Insert: {
          code: string
          name_key: string
          description_key: string
          amount_kopecks: number
          currency?: string
          period_days: number
          is_active?: boolean
          updated_at?: string | null
        }
        Update: {
          code?: string
          name_key?: string
          description_key?: string
          amount_kopecks?: number
          currency?: string
          period_days?: number
          is_active?: boolean
          updated_at?: string | null
        }
        Relationships: []
      }
      blocks: {
        Row: {
          id: string
          blocker_id: string
          blocked_id: string | null
          blocked_email_hash: string
          reason: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          blocker_id: string
          blocked_id?: string | null
          blocked_email_hash: string
          reason?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          blocker_id?: string
          blocked_id?: string | null
          blocked_email_hash?: string
          reason?: string | null
          created_at?: string | null
        }
        Relationships: [
          { foreignKeyName: 'blocks_blocker_id_fkey'; columns: ['blocker_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] },
          { foreignKeyName: 'blocks_blocked_id_fkey'; columns: ['blocked_id']; referencedRelation: 'profiles'; referencedColumns: ['id'] }
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: 'user' | 'moderator' | 'admin'
      gender_type: 'male' | 'female'
      ai_bio_status: 'ready' | 'regenerating' | 'rate_limited' | 'pending'
      photo_status: 'pending' | 'uploaded' | 'processing' | 'processed'
      moderation_status: 'queued' | 'approved' | 'rejected' | 'manual_review'
      message_type: 'text' | 'image' | 'voice'
      message_status: 'sent' | 'delivered' | 'read'
      notification_status: 'unread' | 'read'
      report_type: 'profile' | 'photo'
      report_status: 'new' | 'in_progress' | 'resolved'
      subscription_status: 'active' | 'expired' | 'cancelled' | 'inactive'
      push_kind: 'web' | 'apns' | 'fcm'
      suspension_kind: 'warning' | 'temp_ban' | 'permanent_ban'
    }
  }
}
