export const STATUS_MAP = {
  // AUTH
  AUTH_UNAUTHORIZED: 401,
  AUTH_FORBIDDEN: 403,
  AUTH_SUSPENDED: 403,
  AUTH_EMAIL_BANNED: 403,
  AUTH_MAGIC_LINK_EXPIRED: 401,
  AUTH_MAGIC_LINK_INVALID: 401,
  AUTH_SESSION_EXPIRED: 401,

  // VALIDATION
  VALIDATION_INVALID_INPUT: 422,
  VALIDATION_FILE_TOO_LARGE: 422,
  VALIDATION_FILE_UNSUPPORTED_FORMAT: 422,
  VALIDATION_IMAGE_TOO_SMALL: 422,
  VALIDATION_UNDERAGE: 422,

  // BUSINESS
  LIKE_LIMIT_REACHED: 409,
  LIKE_ALREADY_SENT: 409,
  LIKE_OWN_PROFILE: 422,
  LIKE_TARGET_UNPUBLISHED: 422,
  LIKE_BLOCKED: 422,
  LIKE_GENDER_MISMATCH: 422,
  MATCH_NOT_FOUND: 404,
  CHAT_NOT_PARTICIPANT: 403,
  MESSAGE_EDIT_WINDOW_EXPIRED: 409,
  MESSAGE_NOT_OWNER: 403,
  MESSAGE_NOT_TEXT: 422,
  MESSAGE_ALREADY_DELETED: 409,
  PHOTO_MAX_COUNT: 409,
  PHOTO_NOT_OWNER: 403,
  PHOTO_ONLY_APPROVED_DELETED: 409,
  PHOTO_POSITION_TAKEN: 409,
  PHOTO_STILL_PROCESSING: 409,
  PROFILE_NOT_PUBLISHED: 422,
  PROFILE_GENDER_IMMUTABLE: 422,
  BLOCK_ALREADY_EXISTS: 409,
  BLOCK_SELF: 422,
  BIO_RATE_LIMITED: 429,
  BIO_REGENERATION_IN_FLIGHT: 409,
  SUBSCRIPTION_ALREADY_ACTIVE: 409,
  SUBSCRIPTION_NOT_FOUND: 404,
  REPORT_RATE_LIMITED: 429,
  REPORT_SELF: 422,
  CHAT_INITIATION_LIMIT: 429,

  // PHOTO
  PHOTO_PROCESSING_FAILED: 500,
  PHOTO_MODERATION_FAILED: 500,
  PHOTO_UPLOAD_FAILED: 500,
  PHOTO_DOWNLOAD_FAILED: 500,

  // PAYMENT
  PAYMENT_INIT_FAILED: 502,
  PAYMENT_SIGNATURE_INVALID: 403,
  PAYMENT_AMOUNT_MISMATCH: 422,
  PAYMENT_ORDER_EXPIRED: 409,

  // RATE_LIMIT
  RATE_LIMIT_TOO_MANY_REQUESTS: 429,
  RATE_LIMIT_AUTH_CALLBACK: 429,
  RATE_LIMIT_MESSAGE_SEND: 429,

  // EXTERNAL
  EXTERNAL_OPENAI_FAILED: 502,
  EXTERNAL_DEEPSEEK_FAILED: 502,
  EXTERNAL_OPENAI_TIMEOUT: 504,
  EXTERNAL_TBANK_FAILED: 502,
  EXTERNAL_RESEND_FAILED: 502,
  EXTERNAL_SUPABASE_STORAGE_FAILED: 502,

  // SYSTEM
  SYSTEM_INTERNAL_ERROR: 500,
  SYSTEM_DATABASE_ERROR: 500,
  SYSTEM_TIMEOUT: 504,
  SYSTEM_MAINTENANCE: 503,

  // NOT_FOUND
  NOT_FOUND: 404,

  // IDEMPOTENCY
  IDEMPOTENCY_KEY_MISSING: 422,
  IDEMPOTENCY_KEY_INVALID: 422,
  IDEMPOTENCY_CONFLICT: 409,
} as const

export type ErrorCode = keyof typeof STATUS_MAP
